servergroups:
  web:
    - host: 192.168.1.102
      username: "root"
      password: "putYourPasswordHere"
      port: 22

tasks:
  setup:
    steps:
      - command: cd /home && ./anchor cmdfile.txt
